In [1]:
import glob, os, numpy
from osgeo import gdal

In [2]:
os.chdir("../tif")
tif_list=glob.glob("*.tif")

In [3]:
for tif in tif_list:
    ds = gdal.Open(tif)
    for count in range(1,1+ds.RasterCount):
        print("{} band number {}".format(tif,count))
        print("shape: {}".format(ds.GetRasterBand(count).ReadAsArray().shape))
        print(ds.GetRasterBand(count).ReadAsArray())
        print("===============================")

test3.tif band number 1
shape: (2042, 1982)
[[65 65 65 ... 46 47 47]
 [67 67 68 ... 46 47 47]
 [71 71 71 ... 47 47 47]
 ...
 [54 69 69 ... 46 46 50]
 [65 67 67 ... 44 44 46]
 [47 51 51 ... 44 44 46]]
test3.tif band number 2
shape: (2042, 1982)
[[59 59 59 ... 56 55 55]
 [61 61 62 ... 55 55 55]
 [65 65 65 ... 55 55 55]
 ...
 [65 69 69 ... 65 65 72]
 [80 77 77 ... 58 58 63]
 [56 60 60 ... 60 60 63]]
test3.tif band number 3
shape: (2042, 1982)
[[40 40 41 ... 47 47 47]
 [42 42 42 ... 48 47 47]
 [43 43 45 ... 47 47 47]
 ...
 [41 46 46 ... 38 38 42]
 [50 51 51 ... 38 38 40]
 [38 39 39 ... 38 38 39]]
visualization.tif band number 1
shape: (2042, 1982)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
visualization.tif band number 2
shape: (2042, 1982)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
visualization.tif band number 3
shape: (2042, 1982)
[[  